AWSTemplateFormatVersion: 2010-09-09
Description: >-
  env-protection Experimentation
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  ProtectionWebHook:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: [ "index.ts" ]
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 128
      Timeout: 100
      Description: Simple webhook implementation.
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/github/envprotection/private_key'
      AutoPublishAlias: live
      Environment:
        Variables:
          GH_APP_ID: '{{resolve:ssm:/github/envprotection/app_id}}'
          GH_PRIVATE_KEY: '/github/envprotection/private_key'
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins: [ '*' ]
          AllowMethods: [ GET, POST, PUT, DELETE, PATCH, HEAD ]
