name: Environment Matrix
on:
  workflow_dispatch:
jobs:
  initial-approval:
    name: Initial Approval
    runs-on: ubuntu-22.04
    environment:
      name: PROD approval
    steps:
      - name: Print Approval
        run: echo "Deployment Approved"
  region-az-rollout:
    name: Region AZ Rollout
    needs: initial-approval
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        target:
          - { region: 'us-east-1', az: 'use1-az1' }
          - { region: 'us-east-1', az: 'use1-az3' }
          - { region: 'us-west-2', az: 'usw2-az1' }
          - { region: 'us-west-2', az: 'usw2-az2' }
          - { region: 'eu-west-1', az: 'euw1-az1' }
          - { region: 'eu-west-1', az: 'euw1-az2' }
    uses: .github/workflows/matrix_target.yml@main
    with:
      runner: 'ubuntu-22.04'
      environment: PROD monitoring
      region: ${{ matrix.target.region }}
      az: ${{ matrix.target.az }}


